[package]
name = "chip8-emulator"
version = "0.1.0"
authors = ["Mattia Toso <mtoso@netflix.com>"]
edition = "2018"
description = "A CHIP8 emulator"
license = "MIT"
repository = "https://github.com/mtoso/chip8-emulator"


[dependencies]
