[package]
name = "chip8-emulator"
version = "0.1.0"
authors = ["Mattia Toso <mattia.toso@gmail.com>"]
edition = "2018"
description = "A CHIP8 emulator"
license = "MIT"
repository = "https://github.com/mtoso/chip8-emulator"


[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2.62"